// <auto-generated />
namespace SIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedclearanceandclearancereason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedclearanceandclearancereason));
        
        string IMigrationMetadata.Id
        {
            get { return "201705041034317_added clearance and clearance reason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
