// <auto-generated />
namespace SIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedyearpropertytoteachercourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedyearpropertytoteachercourse));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151701479_added year property to teachercourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
